# -*- coding: utf-8 -*-
# TopSpace 广场 H5 v4 完整生成脚本

lines = []

# HTML头部
lines.append('<!DOCTYPE html>')
lines.append('<html lang="zh-CN">')
lines.append('<head>')
lines.append('    <meta charset="UTF-8">')
lines.append('    <meta name="viewport" content="width=device-width,initial-scale=1.0,maximum-scale=1.0,user-scalable=no">')
lines.append("    <title>TopSpace · 广场</title>")
lines.append('    <style>')
lines.append('* { margin:0; padding:0; box-sizing:border-box; }')
lines.append(':root { --paper:#F5F0E8; --text:#2C2824; --amber:#E8B44C; --rust:#D96B6B; --water:#4A9EB8; --wood:#A0B87A; --earth:#9B7BBF; }')
lines.append('html, body { width:100%; height:100%; overflow:hidden; font-family:-apple-system,"PingFang SC","Helvetica Neue",sans-serif; -webkit-user-select:none; user-select:none; }')
lines.append('')
lines.append('.scene { position:relative; width:100%; height:100%; overflow:hidden; cursor:grab; background:#1A1F30; }')
lines.append('.scene.grabbing { cursor:grabbing; }')
lines.append('')
lines.append('.sky { position:absolute; top:0; left:0; width:12000px; height:100%; z-index:0;')
lines.append('    background:linear-gradient(180deg, #1A1F30 0%, #252B3D 20%, #2E3650 40%, #3D4560 60%, #5A6078 100%); }')
lines.append('.stars { position:absolute; top:0; left:0; width:12000px; height:60%; z-index:1; pointer-events:none; }')
lines.append('.star { position:absolute; border-radius:50%; background:#fff; opacity:0.6; animation: twinkle 3s ease-in-out infinite; }')
lines.append('@keyframes twinkle { 0%,100% { opacity:0.3; transform:scale(1); } 50% { opacity:0.9; transform:scale(1.2); } }')
lines.append('.moon { position:absolute; top:12%; right:15%; width:32px; height:32px; border-radius:50%;')
lines.append('    background:radial-gradient(circle at 40% 40%, #F0EAD0, #D4C880);')
lines.append('    box-shadow:0 0 20px rgba(240,230,180,0.3), 0 0 40px rgba(240,230,180,0.1); z-index:2; }')
lines.append('')
lines.append('.skyline-far { position:absolute; top:0; left:0; width:12000px; height:100%; z-index:2; pointer-events:none; opacity:0.12; filter: blur(3px); }')
lines.append('')
lines.append('.wall-wrap { position:absolute; top:42%; left:0; width:12000px; bottom:0; z-index:5; overflow:visible; }')
lines.append('.wall-body { position:absolute; top:0; left:0; width:100%; height:100%;')
lines.append('    background: repeating-linear-gradient(0deg, transparent, transparent 22px, rgba(0,0,0,0.05) 22px, rgba(0,0,0,0.05) 24px),')
lines.append('                repeating-linear-gradient(90deg, transparent, transparent 68px, rgba(0,0,0,0.04) 68px, rgba(0,0,0,0.04) 70px),')
lines.append('                linear-gradient(180deg, #A09080 0%, #887868 50%, #786858 100%); }')
lines.append('.wall-top { position:absolute; top:-16px; left:-3%; width:106%; display:flex; height:16px; z-index:6; }')
lines.append('.crenel { width:58px; height:16px; background:linear-gradient(180deg, #9A9080, #8A8070); border-radius:2px 2px 0 0; margin-right:22px; box-shadow:0 -1px 3px rgba(0,0,0,0.06); }')
lines.append('.crenel-gap { width:36px; height:16px; }')
lines.append('.wall-body::after { content:""; position:absolute; top:0; left:0; right:0; bottom:0;')
lines.append('    background: linear-gradient(110deg, rgba(255,248,235,0.12) 0%, transparent 40%, transparent 70%, rgba(0,0,0,0.1) 100%),')
lines.append('                radial-gradient(ellipse at 30% 30%, rgba(255,240,210,0.06), transparent 50%);')
lines.append('    pointer-events:none; }')
lines.append('')
lines.append('.wall-plaque { position:absolute; top:12%; transform:translateX(-50%); z-index:10;')
lines.append('    background:linear-gradient(180deg, #3D3020, #2A2015);')
lines.append('    border:3px solid #8B7355; border-radius:4px;')
lines.append('    padding:14px 32px;')
lines.append('    box-shadow:0 4px 12px rgba(0,0,0,0.4), inset 0 1px 0 rgba(255,255,255,0.1), inset 0 -2px 4px rgba(0,0,0,0.3);')
lines.append('}')
lines.append('.wall-plaque::before, .wall-plaque::after { content:""; position:absolute; top:-14px; width:6px; height:14px; background:#8B7355; border-radius:2px; }')
lines.append('.wall-plaque::before { left:18%; }')
lines.append('.wall-plaque::after { right:18%; }')
lines.append('.plaque-text { font-size:18px; font-weight:700; color:#D4A855; letter-spacing:10px;')
lines.append('    text-shadow:0 1px 2px rgba(0,0,0,0.5); font-family:serif; }')
lines.append('')
lines.append('.arch-hole { position:absolute; bottom:0; z-index:8; }')
lines.append('.arch-hole-body { width:90px; height:110px; background:linear-gradient(180deg, #1A1510, #0A0805);')
lines.append('    border-radius:45px 45px 0 0; margin:0 auto;')
lines.append('    box-shadow:inset 0 4px 15px rgba(0,0,0,0.6), 0 -2px 8px rgba(0,0,0,0.3);')
lines.append('    border-top:3px solid rgba(90,75,60,0.4); }')
lines.append('.arch-hole-inner { width:60px; height:75px; background:linear-gradient(180deg, #050302, #080604);')
lines.append('    border-radius:30px 30px 0 0; margin:0 auto; margin-top:12px;')
lines.append('    box-shadow:inset 0 3px 10px rgba(0,0,0,0.9); }')
lines.append('')
lines.append('.tower-silhouette { position:absolute; bottom:0; z-index:4; pointer-events:none; }')
lines.append('')
lines.append('.ground { display:none; }')
lines.append('')
lines.append('.bulletin-frame { position:absolute; bottom:18%; left:0; right:0; height:70%; z-index:20; pointer-events:none; }')
lines.append('.frame-top { position:absolute; top:0; left:0; right:0; height:6px; background:linear-gradient(180deg, #7A7068, #6A6058); border-radius:3px; }')
lines.append('.frame-pole { position:absolute; top:6px; width:8px; height:calc(100% - 6px); background:linear-gradient(90deg, #8A8078, #9A9088, #8A8078); border-radius:2px; }')
lines.append('.frame-pole-l { left:12%; } .frame-pole-r { right:12%; }')
lines.append('.frame-bottom { position:absolute; bottom:0; left:12%; right:12%; height:6px; background:linear-gradient(180deg, #6A6058, #5A5048); border-radius:3px; }')
lines.append('')
lines.append('.vp { position:absolute; top:0; left:0; right:0; bottom:0; overflow:hidden; z-index:25; }')
lines.append('.cv { position:absolute; height:100%; display:flex; align-items:center; gap:0; will-change:transform; }')
lines.append('')
lines.append('.sticky { position:absolute; cursor:pointer; transition: filter 0.2s, transform 0.15s; }')
lines.append('.sticky:hover { filter:brightness(1.04); } .sticky:active { filter:brightness(0.95); }')
lines.append('.sticky-creator { background:#FFF9E0; } .sticky-meet { background:#FFF0F0; } .sticky-rally { background:#EEF5FF; } .sticky-idea { background:#F0FFF0; }')
lines.append('.sticky-body { width:100%; height:100%; border-radius:2px; box-shadow:3px 4px 12px rgba(0,0,0,0.12), 0 0 0 0.5px rgba(0,0,0,0.04); position:relative; overflow:hidden; padding:14px 12px; }')
lines.append('.sticky-body::before { content:""; position:absolute; top:0; left:0; right:0; bottom:0;')
lines.append('    background: radial-gradient(ellipse at 20% 15%, rgba(255,255,255,0.5), transparent 50%),')
lines.append('                radial-gradient(ellipse at 80% 90%, rgba(200,190,170,0.12), transparent 40%);')
lines.append('    pointer-events:none; }')
lines.append('.sticky-corner { position:absolute; bottom:0; right:0; width:18px; height:18px; background:linear-gradient(135deg, transparent 50%, rgba(0,0,0,0.04) 50%); border-radius:0 0 2px 0; }')
lines.append('.pin-tape { position:absolute; top:-6px; left:50%; transform:translateX(-50%) rotate(-8deg); width:50px; height:14px; background:rgba(200,210,160,0.45); border:1px solid rgba(180,200,140,0.3); border-radius:1px; box-shadow:0 1px 3px rgba(0,0,0,0.06); }')
lines.append('.pin-pushpin { position:absolute; top:-8px; left:50%; transform:translateX(-50%); width:12px; height:12px; background:radial-gradient(circle at 35% 35%, #E85555, #AA3333); border-radius:50%; box-shadow:0 2px 4px rgba(0,0,0,0.2), inset 0 -2px 4px rgba(0,0,0,0.1); }')
lines.append('.pin-clip { position:absolute; top:-8px; left:calc(100% - 30px); width:18px; height:20px; border:2.5px solid #9A9080; border-radius:9px 9px 2px 2px; background:transparent; box-shadow:0 2px 4px rgba(0,0,0,0.08); }')
lines.append('')
lines.append('.top-bar { position:absolute; top:0; left:0; right:0; z-index:200; padding:44px 20px 12px; display:flex; align-items:center; justify-content:space-between; background:linear-gradient(180deg, rgba(26,31,48,0.85) 0%, transparent 100%); pointer-events:none; }')
lines.append('.tb-left { width:32px; } .tb-center { flex:1; text-align:center; }')
lines.append('.tb-title { font-size:17px; font-weight:700; color:#F5F0E8; letter-spacing:3px; }')
lines.append('.tb-sub { font-size:10px; color:rgba(245,240,232,0.45); margin-top:2px; letter-spacing:1px; }')
lines.append('.tb-right { display:flex; gap:8px; }')
lines.append('.tb-icon { width:32px; height:32px; border-radius:50%; background:rgba(245,240,232,0.08); border:none; color:rgba(245,240,232,0.6); font-size:14px; cursor:pointer; display:flex; align-items:center; justify-content:center; pointer-events:auto; }')
lines.append('')
lines.append('.loc-tag { position:absolute; top:76px; left:50%; transform:translateX(-50%); font-size:11px; color:rgba(245,240,232,0.5); background:rgba(26,31,48,0.5); padding:4px 14px; border-radius:12px; backdrop-filter:blur(6px); z-index:200; display:flex; align-items:center; gap:5px; letter-spacing:1px; }')
lines.append('.loc-dot { width:5px; height:5px; background:#A0B87A; border-radius:50%; }')
lines.append('')
lines.append('.drag-hint { position:absolute; bottom:16%; left:50%; transform:translateX(-50%); font-size:11px; color:rgba(245,240,232,0.35); z-index:50; display:flex; align-items:center; gap:6px; animation:hintPulse 2.5s ease-in-out infinite; pointer-events:none; white-space:nowrap; background:rgba(26,31,48,0.4); padding:6px 16px; border-radius:14px; }')
lines.append('@keyframes hintPulse { 0%,100%{ opacity:0.3; } 50%{ opacity:0.7; } }')
lines.append('')
lines.append('.bottom-tab { position:absolute; bottom:0; left:0; right:0; height:70px; background:rgba(20,22,32,0.92); backdrop-filter:blur(18px); -webkit-backdrop-filter:blur(18px); border-top:1px solid rgba(232,180,76,0.08); display:flex; justify-content:space-around; align-items:flex-start; padding-top:10px; z-index:300; padding-bottom:env(safe-area-inset-bottom, 0); }')
lines.append('.tab-item { display:flex; flex-direction:column; align-items:center; gap:3px; cursor:pointer; padding:4px 10px; }')
lines.append('.tab-icon { font-size:20px; color:rgba(245,240,232,0.3); transition:color 0.2s; }')
lines.append('.tab-label { font-size:9px; color:rgba(245,240,232,0.3); font-weight:600; transition:color 0.2s; }')
lines.append('.tab-item.on .tab-icon { color:#E8B44C; } .tab-item.on .tab-label { color:#E8B44C; }')
lines.append('.tab-item:not(.on) .tab-icon { filter:grayscale(0.5); opacity:0.42; }')
lines.append('')
lines.append('.toast { position:fixed; bottom:90px; left:50%; transform:translateX(-50%); background:rgba(44,40,36,0.88); color:#F5F0E8; padding:9px 20px; border-radius:20px; font-size:12px; z-index:500; white-space:nowrap; opacity:0; transition:opacity 0.3s; pointer-events:none; }')
lines.append('.toast.show { opacity:1; }')
lines.append('')
lines.append('.detail-overlay { position:fixed; top:0; left:0; right:0; bottom:0; background:rgba(20,22,32,0.7); z-index:400; display:none; align-items:flex-end; justify-content:center; }')
lines.append('.detail-overlay.show { display:flex; }')
lines.append('.detail-sheet { width:100%; max-height:75vh; background:#F5F0E8; border-radius:20px 20px 0 0; padding:24px 20px 40px; transform:translateY(100%); transition:transform 0.35s cubic-bezier(0.32,0.72,0,1); overflow-y:auto; }')
lines.append('.detail-overlay.show .detail-sheet { transform:translateY(0); }')
lines.append('.detail-handle { width:36px; height:4px; background:#D0C8BC; border-radius:2px; margin:0 auto 20px; }')
lines.append('.detail-tag { display:inline-block; padding:3px 12px; border-radius:12px; font-size:11px; font-weight:600; margin-bottom:12px; }')
lines.append('.detail-tag-creator { background:rgba(160,184,122,0.15); color:#7A9A5A; }')
lines.append('.detail-tag-meet { background:rgba(217,107,107,0.15); color:#C05555; }')
lines.append('.detail-tag-rally { background:rgba(74,158,184,0.15); color:#3A8AAA; }')
lines.append('.detail-tag-idea { background:rgba(155,123,191,0.15); color:#7A5AAA; }')
lines.append('.detail-title { font-size:18px; font-weight:700; color:#2C2824; margin-bottom:6px; letter-spacing:1px; }')
lines.append('.detail-meta { font-size:11px; color:#A09888; margin-bottom:16px; display:flex; align-items:center; gap:8px; }')
lines.append('.detail-avatar { font-size:20px; vertical-align:middle; margin-right:4px; }')
lines.append('.detail-text { font-size:13px; line-height:1.8; color:#5A5650; margin-bottom:20px; }')
lines.append('.detail-info { background:rgba(74,158,184,0.06); border:1px solid rgba(74,158,184,0.12); border-radius:12px; padding:14px; margin-bottom:20px; }')
lines.append('.detail-info-row { display:flex; align-items:center; gap:8px; margin-bottom:8px; font-size:12px; color:#6A6258; }')
lines.append('.detail-info-row:last-child { margin-bottom:0; }')
lines.append('.detail-cta { width:100%; padding:14px; border:none; border-radius:14px; font-size:14px; font-weight:600; color:#fff; cursor:pointer; text-align:center; transition:filter 0.2s; }')
lines.append('.detail-cta:active { filter:brightness(0.9); }')
lines.append('.detail-close { width:100%; padding:12px; margin-top:8px; background:rgba(0,0,0,0.04); border:none; border-radius:12px; font-size:13px; color:#8A8478; cursor:pointer; }')
lines.append('    </style>')
lines.append('</head>')
lines.append('<body>')
lines.append('<div class="scene" id="scene">')
lines.append('    <div class="sky" id="skyLayer"></div>')
lines.append('    <div class="stars" id="starsLayer"></div>')
lines.append('    <div class="moon"></div>')
lines.append('    <div class="skyline-far" id="skylineFar"></div>')
lines.append('')
lines.append('    <div class="wall-wrap" id="wallWrap">')
lines.append('        <div class="wall-body"><div class="wall-top" id="wallTop"></div></div>')
lines.append('')
lines.append('        <div class="wall-plaque" style="left:12%;"><div class="plaque-text">明城墙</div></div>')
lines.append('        <div class="wall-plaque" style="left:38%;"><div class="plaque-text">明城墙</div></div>')
lines.append('        <div class="wall-plaque" style="left:64%;"><div class="plaque-text">明城墙</div></div>')
lines.append('        <div class="wall-plaque" style="left:90%;"><div class="plaque-text">明城墙</div></div>')
lines.append('')
lines.append('        <div class="arch-hole" style="left:8%;"><div class="arch-hole-body"><div class="arch-hole-inner"></div></div></div>')
lines.append('        <div class="arch-hole" style="left:32%;"><div class="arch-hole-body"><div class="arch-hole-inner"></div></div></div>')
lines.append('        <div class="arch-hole" style="left:56%;"><div class="arch-hole-body"><div class="arch-hole-inner"></div></div></div>')
lines.append('        <div class="arch-hole" style="left:80%;"><div class="arch-hole-body"><div class="arch-hole-inner"></div></div></div>')
lines.append('    </div>')
lines.append('')
lines.append('    <div class="ground" id="groundLayer"></div>')
lines.append('')
lines.append('    <div class="bulletin-frame">')
lines.append('        <div class="frame-top"></div>')
lines.append('        <div class="frame-pole frame-pole-l"></div>')
lines.append('        <div class="frame-pole frame-pole-r"></div>')
lines.append('        <div class="frame-bottom"></div>')
lines.append('    </div>')
lines.append('')
lines.append('    <div class="vp" id="vp"><div class="cv" id="cv"></div></div>')
lines.append('')
lines.append('    <div class="top-bar">')
lines.append('        <div class="tb-left"></div>')
lines.append('        <div class="tb-center"><div class="tb-title">广 场</div><div class="tb-sub">走走看看 · 真实连接</div></div>')
lines.append('        <div class="tb-right">')
lines.append('            <button class="tb-icon" onclick="showToast(\'搜索 · 开发中\')">&#x1F50D;</button>')
lines.append('            <button class="tb-icon" onclick="showToast(\'消息 · 开发中\')">&#x2709;</button>')
lines.append('        </div>')
lines.append('    </div>')
lines.append('')
lines.append('    <div class="loc-tag"><div class="loc-dot"></div>金陵大陆 · 壹号街区 · 广场</div>')
lines.append('    <div class="drag-hint" id="dragHint">&#x2190; 左右滑动，翻看大家的动态 &#x2192;</div>')
lines.append('')
lines.append('    <div class="bottom-tab">')
lines.append('        <div class="tab-item" onclick="showToast(\'星图 · 开发中\')"><div class="tab-icon">&#x1F5FA;</div><div class="tab-label">星图</div></div>')
lines.append('        <div class="tab-item" onclick="showToast(\'故事 · 开发中\')"><div class="tab-icon">&#x1F4D6;</div><div class="tab-label">故事</div></div>')
lines.append('        <div class="tab-item" onclick="showToast(\'碰撞 · 开发中\')"><div class="tab-icon">&#x26A1;</div><div class="tab-label">碰撞</div></div>')
lines.append('        <div class="tab-item on"><div class="tab-icon">&#x1F3D8;</div><div class="tab-label">广场</div></div>')
lines.append('        <div class="tab-item" onclick="location.href=\'./TopSpace·我的·H5.html\'"><div class="tab-icon">&#x1FA90;</div><div class="tab-label">我的</div></div>')
lines.append('    </div>')
lines.append('</div>')
lines.append('')
lines.append('<div class="detail-overlay" id="detailOverlay" onclick="closeDetail(event)">')
lines.append('    <div class="detail-sheet" onclick="event.stopPropagation()">')
lines.append('        <div class="detail-handle"></div>')
lines.append('        <div class="detail-tag" id="detailTag"></div>')
lines.append('        <div class="detail-title" id="detailTitle"></div>')
lines.append('        <div class="detail-meta" id="detailMeta"></div>')
lines.append('        <div class="detail-text" id="detailText"></div>')
lines.append('        <div class="detail-info" id="detailInfo" style="display:none;"></div>')
lines.append('        <button class="detail-cta" id="detailCta"></button>')
lines.append('        <button class="detail-close" onclick="closeDetail()">关闭</button>')
lines.append('    </div>')
lines.append('</div>')
lines.append('')
lines.append('<div class="toast" id="toast"></div>')
lines.append('')
lines.append('<script>')
lines.append('''var posts = [
    {id:1, type:"creator", who:"手作人·林深", num:"0127", avatar:"🧶", title:"做了个小夜灯", text:"做了一个小夜灯，卖出去三个，收到了第一个陌生人的好评。这种感觉，比任何数据都真实。", tag:"创造者说", tagClass:"detail-tag-creator", time:"2小时前", hearts:12, liked:false, pin:"tape", w:290, h:230, topPct:30, color:"#FFF9E0", accent:"#A0B87A"},
    {id:2, type:"meet", who:"摄影·阿桥", num:"0341", avatar:"📷", title:"周六下午鸡鸣寺拍城市风光", text:"周六下午鸡鸣寺旁边拍城市风光，有人一起吗？带机子不带机子都行，走走看看。", tag:"约 起", tagClass:"detail-tag-meet", time:"4小时前", hearts:8, liked:false, go:3, dt:"周六 14:00", loc:"鸡鸣寺路", pin:"pushpin", w:310, h:250, topPct:50, color:"#FFF0F0", accent:"#D96B6B"},
    {id:3, type:"creator", who:"写作者·白鹿", num:"0078", avatar:"✍️", title:"写了篇「一个人逛博物馆」", text:"写完了一篇关于「一个人逛博物馆」的文章。3000字，改了六遍。发给三个人看，都说安静得像在逛一座空城。", tag:"创造者说", tagClass:"detail-tag-creator", time:"昨天", hearts:23, liked:false, pin:"clip", w:285, h:220, topPct:28, color:"#FFF9E0", accent:"#A0B87A"},
    {id:4, type:"rally", who:"拓圈官方", num:"0000", avatar:"🏛️", title:"拓圈官方寻找30名创造者入驻", text:"寻找30名创造者入驻首批街区。不要求作品完美，只要求你是认真的。首批名额有限，欢迎来聊。", tag:"召集令", tagClass:"detail-tag-rally", time:"1天前", hearts:45, liked:false, dl:"长期有效", pin:"clip", w:300, h:210, topPct:35, color:"#EEF5FF", accent:"#4A9EB8"},
    {id:5, type:"creator", who:"陶艺·云归", num:"0203", avatar:"🏺", title:"第一个陶瓷杯出窑了", text:"第一个陶瓷杯出窑了。有窑变的痕迹，老师说这叫「天意」。我觉得不完美才是最完美的。", tag:"创造者说", tagClass:"detail-tag-creator", time:"2天前", hearts:19, liked:false, pin:"tape", w:295, h:225, topPct:48, color:"#FFF9E0", accent:"#A0B87A"},
    {id:6, type:"meet", who:"咖啡·老陈", num:"0189", avatar:"☕", title:"老门东新店试豆", text:"老门东新开的小店试了，豆子选的是云南日晒。周五下午有人来杯手冲聊聊吗？我请。", tag:"约 起", tagClass:"detail-tag-meet", time:"3天前", hearts:6, liked:false, go:2, dt:"周五 15:00", loc:"老门东", pin:"pushpin", w:305, h:240, topPct:32, color:"#FFF0F0", accent:"#D96B6B"},
    {id:7, type:"idea", who:"城市观察·拾光", num:"0412", avatar:"💡", title:"玄武湖边的长椅", text:"每天早上七点，同一个长椅，同一个老人在看报纸。一个月了，我终于鼓起勇气问他：您看的是什么报？他笑着说：《扬子晚报》，我订了三十年。", tag:"灵光一现", tagClass:"detail-tag-idea", time:"昨天", hearts:38, liked:false, pin:"tape", w:290, h:235, topPct:45, color:"#F0FFF0", accent:"#9B7BBF"},
    {id:8, type:"rally", who:"拓圈官方", num:"0000", avatar:"🏛️", title:"6月主题碰撞会", text:"「城市里的留白空间」特邀建筑设计师对话，名额30人，先到先得。", tag:"召集令", tagClass:"detail-tag-rally", time:"3天前", hearts:31, liked:false, dl:"6月15日", pin:"clip", w:295, h:205, topPct:38, color:"#EEF5FF", accent:"#4A9EB8"}
];''')
lines.append('')
lines.append('function buildStars() {')
lines.append('    var html = \'\';')
lines.append('    for (var i = 0; i < 80; i++) {')
lines.append('        var x = Math.random() * 12000;')
lines.append('        var y = Math.random() * 100;')
lines.append('        var size = 1 + Math.random() * 2;')
lines.append('        var delay = (Math.random() * 4).toFixed(1);')
lines.append('        var dur = (2 + Math.random() * 3).toFixed(1);')
lines.append('        html += \'<div class="star" style="left:\' + x.toFixed(1) + \'px;top:\' + y.toFixed(1) + \'%;width:\' + size.toFixed(1) + \'px;height:\' + size.toFixed(1) + \'px;animation-delay:\' + delay + \'s;animation-duration:\' + dur + \'s"></div>\';')
lines.append('    }')
lines.append('    return html;')
lines.append('}')
lines.append('')
lines.append('function buildNanjingSkyline() {')
lines.append('    var totalW = 12000;')
lines.append('    var s = \'\';')
lines.append('    s += \'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 \' + totalW + \' 500" preserveAspectRatio="none" style="width:100%;height:100%;position:absolute;bottom:0">\';')
lines.append('    var bldgsLeft = [{x:100,w:35,h:55},{x:160,w:28,h:42},{x:220,w:45,h:68},{x:290,w:32,h:48},{x:350,w:50,h:72},{x:420,w:25,h:38},{x:480,w:55,h:82},{x:560,w:30,h:45},{x:620,w:40,h:58},{x:690,w:35,h:52},{x:760,w:50,h:75},{x:840,w:28,h:40}];')
lines.append('    for (var b = 0; b < bldgsLeft.length; b++) { var bb = bldgsLeft[b]; s += \'<rect x="\' + bb.x + \'" y="\' + (325 - bb.h) + \'" width="\' + bb.w + \'" height="\' + bb.h + \'" rx="1" fill="#7A7A7A" opacity="0.4"/>\'; }')
lines.append('    var bldgsMid = [{x:1100,w:35,h:50},{x:1160,w:28,h:42},{x:1220,w:45,h:68},{x:1300,w:32,h:48},{x:1360,w:55,h:82},{x:1440,w:25,h:38},{x:1500,w:40,h:58},{x:1570,w:30,h:45},{x:1640,w:48,h:70}];')
lines.append('    for (var b2 = 0; b2 < bldgsMid.length; b2++) { var bb2 = bldgsMid[b2]; s += \'<rect x="\' + bb2.x + \'" y="\' + (325 - bb2.h) + \'" width="\' + bb2.w + \'" height="\' + bb2.h + \'" rx="1" fill="#7A7A7A" opacity="0.4"/>\'; }')
lines.append('    var bldgsRight = []; for (var i = 0; i < 60; i++) { bldgsRight.push({x: 2000 + i * 75 + Math.random() * 20, w: 25 + Math.random() * 35, h: 35 + Math.random() * 55}); }')
lines.append('    for (var b3 = 0; b3 < bldgsRight.length; b3++) { var bb3 = bldgsRight[b3]; s += \'<rect x="\' + Math.floor(bb3.x) + \'" y="\' + (320 - Math.floor(bb3.h)) + \'" width="\' + Math.floor(bb3.w) + \'" height="\' + Math.floor(bb3.h) + \'" rx="1" fill="#7A7A7A" opacity="0.4"/>\'; }')
lines.append('    s += \'<path d="M0,342 L200,340 L400,337 L600,334 L800,332 L1000,330 L1200,334 L1400,337 L1600,330 L1800,328 L2000,330 L2200,335 L2400,332 L2600,330 L2800,335 L3000,332 L3200,330 L3400,335 L3600,338 L3800,336 L4000,340 L4200,338 L4400,342 L4600,340 L4800,338 L5000,342 L5200,340 L5400,338 L5600,342 L5800,340 L6000,338 L6500,340" fill="none" stroke="#6A6A6A" stroke-width="3" opacity="0.12"/>\';')
lines.append('    s += \'<rect x="0" y="342" width="\' + totalW + \'" height="70" fill="#6A6A6A" opacity="0.05"/>\';')
lines.append('    for (var tr = 0; tr < 40; tr++) { var tx = 100 + tr * 160 + (tr % 3) * 35; var tsize = 10 + (tr % 5) * 4; s += \'<circle cx="\' + tx + \'" cy="\' + (312 - tsize / 2) + \'" r="\' + tsize + \'" fill="#4A5A4A" opacity="0.12"/>\'; }')
lines.append('    s += \'</svg>\'; return s;')
lines.append('}')
lines.append('')
lines.append('function buildWallTop() {')
lines.append('    var totalW = 12000;')
lines.append('    var html = \'\';')
lines.append('    var x = 0;')
lines.append('    while (x < totalW + 100) {')
lines.append('        html += \'<div class="crenel" style="position:absolute;left:\' + x + \'px;top:0"></div>\';')
lines.append('        html += \'<div class="crenel-gap" style="position:absolute;left:\' + (x + 58) + \'px;top:0"></div>\';')
lines.append('        x += 80;')
lines.append('    }')
lines.append('    return html;')
lines.append('}')
lines.append('')
lines.append('function buildSticky(p) {')
lines.append('    var pinHtml = \'\';')
lines.append('    if (p.pin === \'tape\') { pinHtml = \'<div class="pin-tape"></div>\'; }')
lines.append('    else if (p.pin === \'pushpin\') { pinHtml = \'<div class="pin-pushpin"></div>\'; }')
lines.append('    else { pinHtml = \'<div class="pin-clip"></div>\'; }')
lines.append('    var heartIcon = p.liked ? \'❤️\' : \'🤍\';')
lines.append('    var heartColor = p.liked ? \'#D96B6B\' : \'#A09888\';')
lines.append('    var html = \'<div class="sticky" id="sticky-\' + p.id + \'" style="\';')
lines.append('    html += \'left:\' + p.startX + \'px;top:\' + p.topPct + \'%;\';')
lines.append('    html += \'width:\' + p.w + \'px;height:\' + p.h + \'px;" \';')
lines.append('    html += \'onclick="openDetail(\' + p.id + \')">\';')
lines.append('    html += pinHtml;')
lines.append('    html += \'<div class="sticky-body sticky-\' + p.type + \'">\';')
lines.append('    html += \'<div class="sticky-corner"></div>\';')
lines.append('    html += \'<div style="position:absolute;top:10px;left:10px;padding:2px 10px;background:\' + p.accent + \';color:#fff;font-size:9px;font-weight:600;border-radius:10px;z-index:5">\' + p.tag + \'</div>\';')
lines.append('    html += \'<div style="display:flex;align-items:center;gap:6px;margin-top:30px;margin-bottom:8px">\';')
lines.append('    html += \'<span style="font-size:18px">\' + p.avatar + \'</span>\';')
lines.append('    html += \'<div><div style="font-size:12px;font-weight:600;color:#3C3834">\' + p.who + \'</div>\';')
lines.append('    html += \'<div style="font-size:9px;color:#A09888">No.\' + p.num + \' · \' + p.time + \'</div></div></div>\';')
lines.append('    html += \'<div style="font-size:13px;font-weight:700;color:#2C2824;margin-bottom:6px;letter-spacing:0.5px;line-height:1.4">\' + p.title + \'</div>\';')
lines.append('    var shortText = p.text.length > 45 ? p.text.substring(0, 45) + \'…\' : p.text;')
lines.append('    html += \'<div style="font-size:11px;line-height:1.7;color:#6A6258;margin-bottom:8px">\' + shortText + \'</div>\';')
lines.append('    html += \'<div style="position:absolute;bottom:10px;left:10px;right:10px;display:flex;align-items:center;justify-content:space-between">\';')
lines.append('    html += \'<div onclick="event.stopPropagation();toggleHeart(\' + p.id + \')" \';')
lines.append('    html += \'style="display:flex;align-items:center;gap:3px;cursor:pointer;font-size:11px;color:\' + heartColor + \'" \';')
lines.append('    html += \'id="heart-\' + p.id + \'">\';')
lines.append('    html += \'<span>\' + heartIcon + \'</span><span id="heartNum-\' + p.id + \'">\' + p.hearts + \'</span></div>\';')
lines.append('    html += \'<div style="font-size:10px;color:#B0A898">查看详情 ›</div>\';')
lines.append('    html += \'</div></div></div>\';')
lines.append('    return html;')
lines.append('}')
lines.append('')
lines.append('function buildAllCards() {')
lines.append('    var html = \'\';')
lines.append('    var startX = 80;')
lines.append('    var gap = 40;')
lines.append('    for (var i = 0; i < posts.length; i++) {')
lines.append('        posts[i].startX = startX;')
lines.append('        html += buildSticky(posts[i]);')
lines.append('        startX += posts[i].w + gap;')
lines.append('    }')
lines.append('    return { html: html, totalW: startX + 80 };')
lines.append('}')
lines.append('')
lines.append('function openDetail(id) {')
lines.append('    var p = null;')
lines.append('    for (var i = 0; i < posts.length; i++) { if (posts[i].id === id) { p = posts[i]; break; } }')
lines.append('    if (!p) return;')
lines.append('    document.getElementById(\'detailTag\').className = \'detail-tag \' + p.tagClass;')
lines.append('    document.getElementById(\'detailTag\').textContent = p.tag;')
lines.append('    document.getElementById(\'detailTitle\').textContent = p.title;')
lines.append('    document.getElementById(\'detailMeta\').innerHTML = \'<span class="detail-avatar">\' + p.avatar + \'</span>\' + \'<span>\' + p.who + \'</span><span>·</span><span>No.\' + p.num + \'</span><span>·</span><span>\' + p.time + \'</span>\';')
lines.append('    document.getElementById(\'detailText\').textContent = p.text;')
lines.append('    var infoDiv = document.getElementById(\'detailInfo\');')
lines.append('    if (p.type === \'meet\') {')
lines.append('        infoDiv.style.display = \'block\';')
lines.append('        infoDiv.innerHTML = \'<div class="detail-info-row">📅 \' + p.dt + \'</div><div class="detail-info-row">📍 \' + p.loc + \'</div><div class="detail-info-row">👥 \' + p.go + \' 人已参加</div>\';')
lines.append('        document.getElementById(\'detailCta\').style.background = p.accent;')
lines.append('        document.getElementById(\'detailCta\').textContent = \'参加这个约起\';')
lines.append('        document.getElementById(\'detailCta\').onclick = function() { joinMeet(id); };')
lines.append('    } else if (p.type === \'rally\') {')
lines.append('        infoDiv.style.display = \'block\';')
lines.append('        infoDiv.innerHTML = \'<div class="detail-info-row">🏛️ 截止日期：\' + p.dl + \'</div><div class="detail-info-row">👥 名额有限，先到先得</div>\';')
lines.append('        document.getElementById(\'detailCta\').style.background = p.accent;')
lines.append('        document.getElementById(\'detailCta\').textContent = \'我要参加\';')
lines.append('        document.getElementById(\'detailCta\').onclick = function() { joinRally(id); };')
lines.append('    } else {')
lines.append('        infoDiv.style.display = \'none\';')
lines.append('        document.getElementById(\'detailCta\').style.background = p.accent;')
lines.append('        document.getElementById(\'detailCta\').textContent = \'点亮 · 收藏这篇\';')
lines.append('        document.getElementById(\'detailCta\').onclick = function() { showToast(\'已点亮！\'); closeDetail(); };')
lines.append('    }')
lines.append('    document.getElementById(\'detailOverlay\').classList.add(\'show\');')
lines.append('}')
lines.append('')
lines.append('function closeDetail(e) { if (e && e.target !== document.getElementById(\'detailOverlay\')) return; document.getElementById(\'detailOverlay\').classList.remove(\'show\'); }')
lines.append('function joinMeet(id) { for (var i = 0; i < posts.length; i++) { if (posts[i].id === id) { posts[i].go = (posts[i].go || 0) + 1; showToast(\'已参加！去 \' + posts[i].loc + \' 找他们吧\'); break; } } closeDetail(); }')
lines.append('function joinRally(id) { showToast(\'报名成功！期待你的参与\'); closeDetail(); }')
lines.append('')
lines.append('function toggleHeart(id) {')
lines.append('    for (var i = 0; i < posts.length; i++) {')
lines.append('        if (posts[i].id === id) {')
lines.append('            posts[i].liked = !posts[i].liked;')
lines.append('            posts[i].hearts += posts[i].liked ? 1 : -1;')
lines.append('            var heartEl = document.getElementById(\'heart-\' + id);')
lines.append('            var numEl = document.getElementById(\'heartNum-\' + id);')
lines.append('            if (heartEl && numEl) { heartEl.innerHTML = \'<span>\' + (posts[i].liked ? \'❤️\' : \'🤍\') + \'</span><span>\' + posts[i].hearts + \'</span>\'; heartEl.style.color = posts[i].liked ? \'#D96B6B\' : \'#A09888\'; }')
lines.append('            break;')
lines.append('        }')
lines.append('    }')
lines.append('}')
lines.append('')
lines.append('function showToast(msg) { var t = document.getElementById(\'toast\'); t.textContent = msg; t.classList.add(\'show\'); setTimeout(function() { t.classList.remove(\'show\'); }, 2000); }')
lines.append('')
lines.append('var sceneEl, vpEl, cvEl, skyEl, wallEl, groundEl;')
lines.append('var drag = {active:false, startX:0, curScroll:0};')
lines.append('var maxScroll = 0;')
lines.append('var hasDragged = false;')
lines.append('')
lines.append('function bindDrag() {')
lines.append('    sceneEl = document.getElementById(\'scene\');')
lines.append('    vpEl = document.getElementById(\'vp\');')
lines.append('    cvEl = document.getElementById(\'cv\');')
lines.append('    skyEl = document.getElementById(\'skyLayer\');')
lines.append('    wallEl = document.getElementById(\'wallWrap\');')
lines.append('    groundEl = document.getElementById(\'groundLayer\');')
lines.append('    sceneEl.addEventListener(\'mousedown\', onDown);')
lines.append('    sceneEl.addEventListener(\'touchstart\', onDown, {passive:false});')
lines.append('    window.addEventListener(\'mousemove\', onMove);')
lines.append('    window.addEventListener(\'touchmove\', onMove, {passive:false});')
lines.append('    window.addEventListener(\'mouseup\', onUp);')
lines.append('    window.addEventListener(\'touchend\', onUp);')
lines.append('}')
lines.append('function onDown(e) {')
lines.append('    drag.active = true;')
lines.append('    drag.startX = e.type === \'touchstart\' ? e.touches[0].clientX : e.clientX;')
lines.append('    var cur = cvEl.style.transform || \'translateX(0px)\';')
lines.append('    drag.curScroll = parseFloat(cur.replace(\'translateX(\', \'\').replace(\'px)\', \'\')) || 0;')
lines.append('    sceneEl.classList.add(\'grabbing\');')
lines.append('    if (e.cancelable) e.preventDefault();')
lines.append('}')
lines.append('function onMove(e) {')
lines.append('    if (!drag.active) return;')
lines.append('    var x = e.type === \'touchmove\' ? e.touches[0].clientX : e.clientX;')
lines.append('    var dx = x - drag.startX;')
lines.append('    var target = Math.max(-maxScroll, Math.min(0, drag.curScroll + dx));')
lines.append('    applyParallax(target);')
lines.append('    if (Math.abs(target) > 20 && !hasDragged) { hasDragged = true; var hint = document.getElementById(\'dragHint\'); if (hint) hint.style.opacity = \'0\'; }')
lines.append('}')
lines.append('function onUp() { drag.active = false; sceneEl.classList.remove(\'grabbing\'); }')
lines.append('function applyParallax(scrollX) {')
lines.append('    cvEl.style.transform = \'translateX(\' + scrollX + \'px)\';')
lines.append('    skyEl.style.transform = \'translateX(\' + (scrollX * 0.06) + \'px)\';')
lines.append('    wallEl.style.transform = \'translateX(\' + (scrollX * 0.25) + \'px)\';')
lines.append('    groundEl.style.transform = \'translateX(\' + (scrollX * 0.4) + \'px)\';')
lines.append('}')
lines.append('')
lines.append('function init() {')
lines.append('    document.getElementById(\'starsLayer\').innerHTML = buildStars();')
lines.append('    document.getElementById(\'skylineFar\').innerHTML = buildNanjingSkyline();')
lines.append('    document.getElementById(\'wallTop\').innerHTML = buildWallTop();')
lines.append('    var result = buildAllCards();')
lines.append('    document.getElementById(\'cv\').innerHTML = result.html;')
lines.append('    document.getElementById(\'cv\').style.width = result.totalW + \'px\';')
lines.append('    maxScroll = Math.max(0, 12000 - window.innerWidth);')
lines.append('    bindDrag();')
lines.append('}')
lines.append('document.addEventListener(\'DOMContentLoaded\', init);')
lines.append('</script>')
lines.append('</body>')
lines.append('</html>')

# 写入文件
content = '\n'.join(lines)
with open(r'C:/Users/Administrator/Desktop/定稿app页面/TopSpace·广场·H5.html', 'w', encoding='utf-8') as f:
    f.write(content)

print('生成完成！文件大小:', len(content), '字节')
